<a href="https://colab.research.google.com/github/imdhanush13/Crop-Damage-level-prediction/blob/main/Crop_Damage_level_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
#Necessary packages
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

In [91]:
#Load dataset
df=pd.read_csv("/content/Crop_Agriculture_Data_2.csv")
df

ID  Estimated_Insects_Count Crop_Type     Soil_Type  \
0      F00000001                      188    Kharif      Alluvial   
1      F00000003                      209    Kharif      Alluvial   
2      F00000004                      257    Kharif      Alluvial   
3      F00000005                      257    Kharif  Black-Cotton   
4      F00000006                      342    Kharif      Alluvial   
...          ...                      ...       ...           ...   
88853  F00155935                     3337    Kharif      Alluvial   
88854  F00155938                     3516    Kharif      Alluvial   
88855  F00155939                     3516    Kharif      Alluvial   
88856  F00155942                     3702    Kharif      Alluvial   
88857  F00155945                     3895    Kharif      Alluvial   

      Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0               Insecticides                  0                  0   
1               Insecticides                  0                  0   
2               Insecticides                  0                  0   
3               Insecticides                  0                  0   
4               Insecticides                  0                  0   
...                      ...                ...                ...   
88853             Herbicides                 10                 12   
88854             Herbicides                 10                 20   
88855             Herbicides                 15                 40   
88856             Herbicides                 10                 25   
88857             Herbicides                 20                 37   

       Number_Weeks_Quit   Season     Crop_Damage  
0                      0   Summer  Minimal Damage  
1                      0  Monsoon  Partial Damage  
2                      0  Monsoon  Partial Damage  
3                      0  Monsoon  Partial Damage  
4                      0  Monsoon  Partial Damage  
...                  ...      ...             ...  
88853                 44   Winter  Minimal Damage  
88854                 38   Summer  Minimal Damage  
88855                  8  Monsoon  Minimal Damage  
88856                 18   Winter  Minimal Damage  
88857                  7   Winter  Minimal Damage  

[88858 rows x 10 columns]

In [92]:
# Encode categorical variables
for column in ['Crop_Damage', 'Season', 'ID', 'Crop_Type', 'Soil_Type', 'Pesticide_Use_Category']:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])

In [93]:
df

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0          0                      188          0          0   
1          1                      209          0          0   
2          2                      257          0          0   
3          3                      257          0          1   
4          4                      342          0          0   
...      ...                      ...        ...        ...   
88853  88853                     3337          0          0   
88854  88854                     3516          0          0   
88855  88855                     3516          0          0   
88856  88856                     3702          0          0   
88857  88857                     3895          0          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           2                  0                  0   
1                           2                  0                  0   
2                           2                  0                  0   
3                           2                  0                  0   
4                           2                  0                  0   
...                       ...                ...                ...   
88853                       1                 10                 12   
88854                       1                 10                 20   
88855                       1                 15                 40   
88856                       1                 10                 25   
88857                       1                 20                 37   

       Number_Weeks_Quit  Season  Crop_Damage  
0                      0       1            0  
1                      0       0            1  
2                      0       0            1  
3                      0       0            1  
4                      0       0            1  
...                  ...     ...          ...  
88853                 44       2            0  
88854                 38       1            0  
88855                  8       0            0  
88856                 18       2            0  
88857                  7       2            0  

[88858 rows x 10 columns]

In [94]:
# Split the data
x = df.drop(['Crop_Damage'], axis=1)
y = df['Crop_Damage']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

# **DecisionTreeClassifier**

In [95]:
Classifier=DecisionTreeClassifier()
Classifier.fit(x_train,y_train)


DecisionTreeClassifier()

In [96]:
y_pred = Classifier.predict(x_test)


In [97]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[12694  1849   343]
 [ 1578   706   155]
 [  252   154    41]]
              precision    recall  f1-score   support

           0       0.87      0.85      0.86     14886
           1       0.26      0.29      0.27      2439
           2       0.08      0.09      0.08       447

    accuracy                           0.76     17772
   macro avg       0.40      0.41      0.41     17772
weighted avg       0.77      0.76      0.76     17772



# **GaussianNB**

In [98]:
np = GaussianNB()
np.fit(x_train,y_train)


GaussianNB()

In [99]:
y_pred2=np.predict(x_test)


In [100]:

print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[14224   662     0]
 [ 2053   386     0]
 [  363    84     0]]
              precision    recall  f1-score   support

           0       0.85      0.96      0.90     14886
           1       0.34      0.16      0.22      2439
           2       0.00      0.00      0.00       447

    accuracy                           0.82     17772
   macro avg       0.40      0.37      0.37     17772
weighted avg       0.76      0.82      0.79     17772



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **RandomForestClassifier**

In [101]:
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [102]:
y_pred3=rf.predict(x_test)

In [103]:
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

[[14439   423    24]
 [ 1944   449    46]
 [  305   124    18]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.91     14886
           1       0.45      0.18      0.26      2439
           2       0.20      0.04      0.07       447

    accuracy                           0.84     17772
   macro avg       0.51      0.40      0.41     17772
weighted avg       0.79      0.84      0.80     17772



# **XGBClassifier**

In [104]:
model = XGBClassifier()
model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [105]:
y_pred4=rf.predict(x_test)

In [106]:
print(confusion_matrix(y_test,y_pred4))
print(classification_report(y_test,y_pred4))

[[14439   423    24]
 [ 1944   449    46]
 [  305   124    18]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.91     14886
           1       0.45      0.18      0.26      2439
           2       0.20      0.04      0.07       447

    accuracy                           0.84     17772
   macro avg       0.51      0.40      0.41     17772
weighted avg       0.79      0.84      0.80     17772



# **KNeighborsClassifier**

In [107]:
model=KNeighborsClassifier(n_neighbors=9)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [108]:
y_pred=model.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[14447   433     6]
 [ 2192   243     4]
 [  384    63     0]]


In [109]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.97      0.91     14886
           1       0.33      0.10      0.15      2439
           2       0.00      0.00      0.00       447

    accuracy                           0.83     17772
   macro avg       0.39      0.36      0.35     17772
weighted avg       0.76      0.83      0.78     17772



In [110]:
y_pred=model.predict(x_test)
results=pd.DataFrame({'Actual':y_test,'Predictions':y_pred})
results.head(5)

Actual  Predictions
5939        0            0
7700        0            0
19701       0            0
36396       0            0
39960       0            0

# **LogisticRegression**

In [111]:
Classifier=LogisticRegression(solver='liblinear')
Classifier.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [112]:
y_test_hat=Classifier.predict(x_test)
res=pd.DataFrame({'Actual':y_test,'Predictions':y_test_hat})
res.head(5)

Actual  Predictions
5939        0            0
7700        0            0
19701       0            0
36396       0            0
39960       0            0

# **Accuracy**

In [113]:
y_train_hat=Classifier.predict(x_train)
print(accuracy_score(y_train,y_train_hat))

0.8320344371606223


In [114]:
print(accuracy_score(y_test,y_test_hat))

0.8341773576412334
